# Auto-generated by configure.  Do not edit by hand; re-run
# ./configure to regenerate.

GS_WEBKIT_PREFIX        = /usr/GNUstep
GS_WEBKIT_ENABLE_DEBUG  = 0

GS_WEBKIT_WPE_CFLAGS    = -I/usr/include/wpe-webkit-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/libsoup-3.0 -I/usr/include/libmount -I/usr/include/blkid -pthread -isystem /usr/include/mit-krb5 -I/usr/include/wpe-1.0 -I/usr/include/wpe-fdo-1.0 -DWPE_ENABLE_XKB=1  -DGS_WEBKIT_WPE_API_2=1
GS_WEBKIT_WPE_LIBS      = -lWPEWebKit-2.0 -lsoup-3.0 -lgmodule-2.0 -pthread -lglib-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lWPEBackend-fdo-1.0 -lwpe-1.0 

GS_WEBKIT_WAYLAND_LIBS  = -lwayland-server 

GS_WEBKIT_SOUP_CFLAGS   = -I/usr/include/libsoup-3.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/libmount -I/usr/include/blkid -pthread -isystem /usr/include/mit-krb5  -DGS_WEBKIT_HAVE_SOUP=1
GS_WEBKIT_SOUP_LIBS     = -lsoup-3.0 -lgmodule-2.0 -pthread -lglib-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 

GS_WEBKIT_XKB_CFLAGS    =  -DGS_WEBKIT_HAVE_XKB=1
GS_WEBKIT_XKB_LIBS      = -lxkbcommon 

GS_WEBKIT_EGL_CFLAGS    =  -DGS_WEBKIT_HAVE_EGL=1
GS_WEBKIT_EGL_LIBS      = -lEGL 
